# .github/actions/python-test-action/action.yml
name: Python Test Action
description: Runs Python unit tests
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run Python tests
      run: python -m unittest discover
      shell: bash