# .github/workflows/call-composite-action.yml
name: Call Python Test Action

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run Python Test Action
        uses: mtaori/gh-composite-action/.github/actions/python-test-action@main